"""add_ai_scoring_and_fiber_to_meals

Revision ID: 051159291039
Revises: cfb652645e85
Create Date: 2026-06-18 15:18:46.976042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051159291039'
down_revision: Union[str, None] = 'cfb652645e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('total_fiber', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('oil_absorption_score', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('ultra_processing_score', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('hidden_ingredients_risk', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('ai_analysis_details', sa.JSON(), nullable=True))
    op.drop_column('meals', 'ingredients_analysis_json')
    op.drop_column('meals', 'fiber')
    op.drop_column('meals', 'protein')
    op.drop_column('meals', 'fat')
    op.drop_column('meals', 'carbohydrates')
    op.drop_column('meals', 'calories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('calories', sa.FLOAT(), nullable=True))
    op.add_column('meals', sa.Column('carbohydrates', sa.FLOAT(), nullable=True))
    op.add_column('meals', sa.Column('fat', sa.FLOAT(), nullable=True))
    op.add_column('meals', sa.Column('protein', sa.FLOAT(), nullable=True))
    op.add_column('meals', sa.Column('fiber', sa.FLOAT(), nullable=True))
    op.add_column('meals', sa.Column('ingredients_analysis_json', sa.VARCHAR(), nullable=True))
    op.drop_column('meals', 'ai_analysis_details')
    op.drop_column('meals', 'hidden_ingredients_risk')
    op.drop_column('meals', 'ultra_processing_score')
    op.drop_column('meals', 'oil_absorption_score')
    op.drop_column('meals', 'total_fiber')
    # ### end Alembic commands ###
