"""Еще раз выполняю миграцию

Revision ID: 2c9629bb56e3
Revises: cfb652645e85
Create Date: 2026-06-19 06:05:23.796912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9629bb56e3'
down_revision: Union[str, None] = 'cfb652645e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('total_fiber', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('oil_absorption_score', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('ultra_processing_score', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('hidden_ingredients_risk', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('ai_analysis_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'ai_analysis_details')
    op.drop_column('meals', 'hidden_ingredients_risk')
    op.drop_column('meals', 'ultra_processing_score')
    op.drop_column('meals', 'oil_absorption_score')
    op.drop_column('meals', 'total_fiber')
    # ### end Alembic commands ###
