"""Add food quality fields to Meal model

Revision ID: cfb652645e85
Revises: 
Create Date: 2026-06-18 06:30:20.457382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb652645e85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('ai_comment', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('processing_level', sa.Enum('WHOLE', 'MINIMALLY_PROCESSED', 'ULTRA_PROCESSED', name='processinglevel'), nullable=True))
    op.add_column('meals', sa.Column('satiety_index', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('micronutrient_density', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='micronutrientdensity'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'micronutrient_density')
    op.drop_column('meals', 'satiety_index')
    op.drop_column('meals', 'processing_level')
    op.drop_column('meals', 'ai_score')
    op.drop_column('meals', 'ai_comment')
    # ### end Alembic commands ###
